### ISSUE TITLE
No source, feels like just a cheat

### ISSUE THREAD

**Issue by RedBrumbler** [Uuketi/Anti-Tag-Freeze#1]
There is no source code and as such we do not want this to be posted on the modding discord.

also it just feels like a cheat to not have the tag freeze.

**Comment by RedBrumbler** [comment]
it's not even anti freeze it's magic monki

**Comment by Uuketi** [comment]
Yes magic monki without the teleport and without the public part thank you for noticing dad

**Comment by Uuketi** [comment]
source has been added
